name: Blue-Green Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-bluegreen:${{ github.sha }} .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-bluegreen:${{ github.sha }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            ACTIVE=$(cat /opt/deploy/active_env)

            if [ "$ACTIVE" = "blue" ]; then
              TARGET=green
              PORT=8082
            else
              TARGET=blue
              PORT=8081
            fi

            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-bluegreen:${{ github.sha }}

            docker rm -f $TARGET || true

            docker run -d --restart unless-stopped               --name $TARGET               -e APP_VERSION=${{ github.sha }}               -p $PORT:5000               ${{ secrets.DOCKER_USERNAME }}/flask-bluegreen:${{ github.sha }}

            for i in {1..10}; do
              curl -f http://localhost:$PORT/health && break
              sleep 10
            done

            sudo sed -i             "s|proxy_pass http://localhost:.*|proxy_pass http://localhost:$PORT;|"             /etc/nginx/sites-available/default

            sudo nginx -t
            sudo systemctl reload nginx

            echo $TARGET > /opt/deploy/active_env
